var projects = [
  {
    name: "gitDrunk",
    description: "Look up cocktails based on the ingredients you have at home.",
    image: "images/portfolio/gitDrunk.jpg",
    modal: "#modal-01",
    modalImage: "images/portfolio/modals/m-gitDrunk.jpg",
    tags: "HTML, CSS, Javascript",
    tryIt: "https://party-of-five.github.io/gitDrunk/",
    details: "https://github.com/Party-of-Five/gitDrunk",
    id: "modal-01",
  },
  {
    name: "gitLit",
    description:
      "A revamp of gitDrunk using React and the addition of a backend via Mongo.",
    image: "images/portfolio/gitlit.jpg",
    modal: "#modal-02",
    modalImage: "images/portfolio/modals/m-gitlit.jpg",
    tags: "Javascript, HTML, Mongo, MongoDB Atlas, CSS, React",
    tryIt: "https://gitlit-app.herokuapp.com/",
    details: "https://github.com/J-A-M-M-S/gitLit",
    id: "modal-02",
  },
  {
    name: "Note Taker",
    description: "Note taking application",
    image: "images/portfolio/noteTaker.jpg",
    modal: "#modal-03",
    modalImage: "images/portfolio/modals/m-noteTaker.jpg",
    tags: "Javascript, HTML, CSS, Express",
    tryIt: "https://note-taker-ashley.herokuapp.com/",
    details: "https://github.com/AshleyLerma/NoteTaker",
    id: "modal-03",
  },
  {
    name: "Weather Dashboard",
    description: "Weather checking application",
    image: "images/portfolio/weatherApp.jpg",
    modal: "#modal-04",
    modalImage: "images/portfolio/modals/m-weatherApp.jpg",
    tags: "HTML, CSS, Javascript",
    tryIt: "https://ashleylerma.github.io/Weather-Dashboard/",
    details: "https://github.com/AshleyLerma/Weather-Dashboard",
    id: "modal-04",
  },
  {
    name: "Office Quiz",
    description: "Test your knowledge of the hit show The Office.",
    image: "images/portfolio/quiz.jpg",
    modal: "#modal-05",
    modalImage: "images/portfolio/modals/m-quiz.jpg",
    tags: "Javascript, HTML, CSS",
    tryIt: "https://ashleylerma.github.io/codeQuiz/",
    details: "https://github.com/AshleyLerma/codeQuiz",
    id: "modal-05",
  },
  {
    name: "Day Planner",
    description: "Day scheduler application.",
    image: "images/portfolio/planner.jpg",
    modal: "#modal-06",
    modalImage: "images/portfolio/modals/m-planner.jpg",
    tags: "Javascript, HTML, CSS",
    tryIt: "https://ashleylerma.github.io/dayPlanner/",
    details: "https://github.com/AshleyLerma/dayPlanner",
    id: "modal-06",
  },
];
export default projects;
