var projects = [
  {
    name: "gitDrunk",
    description: "Look up cocktails based on the ingredients you have at home.",
    image: "images/portfolio/gitDrunk.jpg",
    modal: "#modal-01",
    modalImage: "images/portfolio/modals/m-gitDrunk.jpg",
    tags: ["html", "css", "javascript"],
    tryIt: "https://party-of-five.github.io/gitDrunk/",
    details: "https://github.com/Party-of-Five/gitDrunk",
  },
  {
    name: "BagIt",
    description: "Grocery List App",
    image: "images/portfolio/bagit.jpg",
    modal: "#modal-02",
    modalImage: "images/portfolio/modals/m-bagit.jpg",
    tags: [],
    tryIt: "",
    details: "",
  },
  {
    name: "Note Taker",
    description: "Note taking application",
    image: "images/portfolio/noteTaker.jpg",
    modal: "#modal-03",
    modalImage: "images/portfolio/modals/m-noteTaker.jpg",
    tags: [],
    tryIt: "",
    details: "",
  },
  {
    name: "Weather Dashboard",
    description: "Weather checking application",
    image: "images/portfolio/weatherApp.jpg",
    modal: "#modal-04",
    modalImage: "images/portfolio/modals/m-weatherApp.jpg",
    tags: [],
    tryIt: "",
    details: "",
  },
  {
    name: "Office Quiz",
    description: "Test your knowledge of the hit show The Office.",
    image: "images/portfolio/quiz.jpg",
    modal: "#modal-05",
    modalImage: "images/portfolio/modals/m-quiz.jpg",
    tags: [],
    tryIt: "",
    details: "",
  },
  {
    name: "Day Planner",
    description: "Day scheduler application.",
    image: "images/portfolio/planner.jpg",
    modal: "#modal-06",
    modalImage: "images/portfolio/modals/m-planner.jpg",
    tags: [],
    tryIt: "",
    details: "",
  },
];
export default projects;
